### ISSUE TITLE
Create installs into fixed path

### ISSUE THREAD

**Issue by davidkarlsen** [wso2-attic/docker-common#7]
The install is not so flexible - as it includes version number (2.1.0) in the path - and hence becomes a moving target - if the path could be fixed it would be easier to configure bindmounts etc.

```
drwxr-xr-x 2 wso2user wso2  26 Mar 17 13:56 172.18.0.2
drwxr-xr-x 8 wso2user wso2 255 Mar 16 12:51 jdk-8u112
drwxrwxr-x 1 wso2user wso2  68 Mar 17 13:56 wso2am-2.1.0
wso2user@498c0937865d:/mnt$ pwd
/mnt
wso2user@498c0937865d:/mnt$
```

**Comment by davidkarlsen** [comment]
The same goes for all configuration - it's a bit of a hassle to have to bind-mount one and one file over the default ones in order to configure the container for your environment.

**Comment by chamilad** [comment]
I'm not exactly clear on the problem here. Is it the `2.1.0` on the path `/mnt/wso2am-2.1.0`?

**Comment by davidkarlsen** [comment]
Yes - it would be cleaner if it was on a fixed path such as /app or /mnt/wso2am - having a symlink would fix it too - generally anything that will make it more like http://12factor.net to run

**Comment by chamilad** [comment]
+1

I assume you're using WSO2 Puppet modules to configure the Docker images. If that is the case, the name of the symlink that is created at `/mnt` can be configured so that it wouldn't contain the product name.

Navigate to `PUPPET_HOME/hieradata/dev/wso2/common.yaml` file. There is a field with key `wso2::carbon_home_symlink` (around line 23 at the moment). Change this so that reflects something like the following.

```yaml
wso2::carbon_home_symlink: "/mnt/%{::product_name}"
```
This should result in the product version agnostic sym link at `/mnt/wso2am`. :)

**Comment by chamilad** [comment]
@imesh @lasanthaS Maybe we can make the above as the default pattern for sym link generation, seeing as the product version information could anyway be embedded in the Docker image tag? If this feels like a Docker only scenario, maybe we could have this be overridden at the platform level common data file?

**Comment by imesh** [comment]
+1 for the suggestion David! 

All WSO2 product distributions contain the product version in their folder names. Up to now we have not changed that in deployments. It's true that it will be easier to manage volume mounts and Docker COPY commands if the product path does not contain the product version.

@chamilad +1 the proposal!
